---
name: Lint Code Base (Clippy)

on:
  pull_request:
    branches: [main]

jobs:
  lint-clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install required Rust version
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.59.0"
          components: clippy
          override: true
      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
