---
name: Release

on:
  push:
    branches: [release-main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13
    - name: Add conventional-commits plugin
      run: npm install conventional-changelog-conventionalcommits
      working-directory: .github/workflows
    - name: Release to GitHub
      working-directory: .github/workflows
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_AUTHOR_NAME: webmencoder-bot
        GIT_AUTHOR_EMAIL: info@example.com
        GIT_COMMITTER_NAME: webmencoder-bot
        GIT_COMMITTER_EMAIL: info@example.com
      run: npx semantic-release
